from text_cnn import TextCNN

NUM_FILTERS = 2
FILTER_SIZES = [2, 3, 5]
MAX_WORD = 40
EMBEDDING_LENGTH = 300
NUM_CLASSES = 2

model = TextCNN(NUM_FILTERS, FILTER_SIZES, MAX_WORD, EMBEDDING_LENGTH, NUM_CLASSES)


